version: "3.8"
services:
  web:
    build:
      context: ./dist/packages/web
      dockerfile: dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - api

  api:
    build:
      context: ./dist/packages/api
      dockerfile: dockerfile
    depends_on:
      - database
    ports:
      - "5000:5000"
    environment:
      PORT: 5000

  worker:
    build:
      context: ./dist/packages/worker
      dockerfile: dockerfile
    depends_on:
      - database
      - mqtt

  database:
    image: postgres:15.0-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: super_password

  mqtt:
    image: eclipse-mosquitto:2
    restart: always
    ports:
      - "1883:1883"
