name: Main
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  continuous_integration:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.x.x'

      - run: dotnet tool restore
        
      - run: dotnet restore
        
      - run: dotnet build --no-restore
        
      - run: dotnet test --no-restore --collect:"XPlat Code Coverage" --results-directory "./test-results"
      
      - run: dotnet tool run reportgenerator
        
      - name: Upload coverage report artifact
        uses: actions/upload-artifact@v2.2.3
        with:
          name: CoverageReport # Artifact name        
          path: coveragereport